---
title: "Analysis of upstrapping simulation results"
output:
  html_document:
    toc: true
    toc_float: true
---

# Load packages

```{r load-packages}
library(tidyverse)
library(dagitty)
library(broom)
library(gridExtra)
```



# Notes about timings

- Getting truth from `get_quantities_from_data`:
    - 1000 iterations: 3 minutes
    - 5000 iterations: 15 minutes (smoother than 1000)
- Getting upstrap estimates from `get_quantities_from_data`:
    - Train size = 500: 3.5 minutes (1000 iters), 13.8 minutes (5000 iters)

Timing calculations (for one parameter set):

```{r eval=FALSE}
3*(1+100*5)/(60*24)
15*(1+100*5)/(60*24)
30*(1+100*5)/(60*24)

3*(1+100*3)/(60*24)
15*(1+100*3)/(60*24)
30*(1+100*3)/(60*24)

3*(1+50*5)/(60*24)
15*(1+50*5)/(60*24)
30*(1+50*5)/(60*24)
```



# Analyze simulation results

Run parameter setup code:

```{r}
source("functions_run_setup_sim.R")
```

```{r}
compute_results <- function(results) {
    std_err <- sapply(results, function(results_mat) {
        sd(results_mat["estim",])
        # mean(results_mat["se",])
    })
    tibble(
        sample_size = as.integer(names(std_err)),
        se = std_err
    )
}

get_results <- function(sim_results, train_sample_sizes) {
    ## Truth
    se_truth <- compute_results(sim_results$truth)
    se_truth <- se_truth %>%
        mutate(type = "truth")

    ## Estimates
    se_list_upstrap <- lapply(sim_results$estimates_upstrap, function(res_this_train_n) {
        res <- lapply(res_this_train_n, compute_results)
        bind_rows(res, .id = "rep")
    })
    names(se_list_upstrap) <- paste("n =", train_sample_sizes)
    se_upstrap <- bind_rows(se_list_upstrap, .id = "type")
    se_upstrap <- se_upstrap %>%
        group_by(type, sample_size) %>%
        summarize(
            se_min = min(se),
            se_p25 = quantile(se, 0.25),
            se_med = median(se),
            se_p75 = quantile(se, 0.75),
            se_max = max(se)
        )

    list(truth = se_truth, upstrap = se_upstrap)
}

plot_results <- function(res) {
    p <- ggplot(res$upstrap, aes(x = factor(sample_size), y = se_med, color = type)) +
        geom_pointrange(aes(ymin = se_p25, ymax = se_p75), position = position_dodge(width = 0.5)) +
        geom_point(data = res$truth, aes(x = factor(sample_size), y = se, color = type), color = "black", size = 4) +
        theme_classic() +
        labs(x = "Target sample size", y = "Standard error", color = "Observed\nsample\nsize")
    p
}
```

```{r}
result_file_names <- file.path("..", "..", "data", "extdata", paste0("sim_results", 1:36, ".rds"))

results_list <- lapply(seq_along(result_file_names), function(i) {
    sim_results <- read_rds(result_file_names[i])
    results <- get_results(sim_results, train_sample_sizes = c(1000, 2000, 4000))
    results
})

plot_list <- lapply(seq_along(result_file_names), function(i) {
    results <- results_list[[i]]
    param_set_index <- str_extract(result_file_names[i], "results[0-9]+") %>% str_replace("results", "") %>% as.integer()
    title <- paste0("DAG ", parameter_combos$dag_index[param_set_index], ". Noise SD: ", parameter_combos$noise_sd[param_set_index])
    plot_results(results) + labs(title = title)
})
```

```{r}
num_rows <- 4
num_cols <- 9
pdf("../../results/results.pdf", width = num_cols*5.5, height = num_rows*3)
do.call(grid.arrange, c(plot_list, nrow = num_rows, ncol = num_cols))
dev.off()

num_rows <- 4
num_cols <- 3
plot_idx_subs <- which(parameter_combos$dag_index %in% c(4,7,8))
plot_list_subs <- plot_list[plot_idx_subs]
pdf("../../results/results_subs.pdf", width = num_cols*5.5, height = num_rows*3)
do.call(grid.arrange, c(plot_list_subs, nrow = num_rows, ncol = num_cols))
dev.off()

pdf("../../results/dags.pdf", width = 9, height = 9)
par(mfrow = c(3,3))
for (i in seq_along(list_dags)) {
    plot(list_dags[[i]], abbreviate.names = FALSE)
}
dev.off()
```

```{r}
showAY <- function(dag) {
    print(exposures(dag))
    print(outcomes(dag))
    print(adjustmentSets(dag))
}

for (dag in list_dags) {
    cat("========================================\n")
    showAY(dag)
}
```



# Session Info

```{r}
sessionInfo()
```